# Generated by Django 2.2.27 on 2022-03-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='painting',
            name='medium',
            field=models.ManyToManyField(blank=True, to='base.Medium'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='style',
            field=models.ManyToManyField(blank=True, to='base.Style'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='subject',
            field=models.ManyToManyField(blank=True, to='base.Subject'),
        ),
    ]
