# Generated by Django 3.2 on 2022-03-06 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220306_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='base.artist'),
        ),
    ]
