# Generated by Django 3.2 on 2022-03-06 10:11

import base.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_painting_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='created_year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), base.models.max_value_current_year]),
        ),
        migrations.AlterField(
            model_name='painting',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
