# Generated by Django 3.2 on 2022-03-07 10:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220307_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='orientation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='shipping',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
