# Generated by Django 3.2 on 2022-03-07 11:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220307_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistry',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='color',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='introduction',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='material',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='size',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='specification',
            field=ckeditor.fields.RichTextField(blank=True, max_length=150, null=True),
        ),
    ]
